/**
 * Loads condition data from data/conditions.json (generated by the enricher script).
 * Falls back to mock conditions if the file doesn't exist.
 * Only runs server-side (Next.js Server Components / generateStaticParams).
 */
import path from 'path'
import { conditions as mockConditions } from './mock-data'
import type { Condition } from './types'

let _cache: Condition[] | null = null

export function loadConditions(): Condition[] {
  if (_cache) return _cache

  try {
    // Only use fs on the server
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const fs = require('fs') as typeof import('fs')
    const filePath = path.join(process.cwd(), 'data', 'conditions.json')
    const raw = JSON.parse(fs.readFileSync(filePath, 'utf8')) as Array<{
      slug: string
      url: string
      title: string
      category?: string
      subcategory?: string
      description?: string
      symptoms?: string[]
      treatments?: string[]
      whenToSeekCare?: string
      specialties?: string[]
      source?: string
      sourceUrl?: string
      lastModified?: string
    }>

    _cache = raw.map((c) => ({
      slug:          c.slug,
      name:          c.title,
      description:   c.description ?? '',
      symptoms:      c.symptoms ?? [],
      treatments:    c.treatments ?? [],
      whenToSeekCare: c.whenToSeekCare ?? undefined,
      specialties:   c.specialties ?? [],
      category:      c.category,
      subcategory:   c.subcategory,
      source:        c.source ?? '1177.se',
      sourceUrl:     c.sourceUrl ?? c.url,
      lastModified:  c.lastModified,
    }))

    return _cache
  } catch {
    // File doesn't exist yet — fall back to mock data
    _cache = mockConditions
    return _cache
  }
}
